from __future__ import annotations

import json
from typing import Any, AsyncIterator, Iterable

from chromadb.api.models.Collection import Collection
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field, field_validator

from db.chroma_client import get_collection
from services.generator import AnswerSource, generate_answer
from services.retriever import retrieve_relevant_chunks

router = APIRouter()
documents_router = APIRouter()


class ChatMessage(BaseModel):
    role: str
    content: str


class QueryRequest(BaseModel):
    question: str
    chat_history: list[ChatMessage] = Field(default_factory=list)
    filter_documents: list[str] | None = None

    @field_validator("question")
    @classmethod
    def validate_question(cls, value: str) -> str:
        normalized = value.strip()
        if not normalized:
            raise ValueError("question must not be empty")
        return normalized

    @field_validator("filter_documents")
    @classmethod
    def validate_filter_documents(cls, value: list[str] | None) -> list[str] | None:
        if value is None:
            return None

        cleaned = [item.strip() for item in value if isinstance(item, str) and item.strip()]
        return cleaned or None


class DocumentsResponse(BaseModel):
    documents: list[str]


def _extract_sources(context_chunks: Iterable[dict[str, Any]]) -> list[AnswerSource]:
    """Build a de-duplicated list of sources from retrieved chunks."""
    sources: list[AnswerSource] = []
    seen: set[tuple[str, int]] = set()

    for chunk in context_chunks:
        source = chunk.get("source")
        page_number = chunk.get("page_number")
        if isinstance(source, str) and isinstance(page_number, int):
            key = (source, page_number)
            if key not in seen:
                seen.add(key)
                sources.append({"source": source, "page": page_number})

    return sources


async def _stream_answer_response(
    question: str,
    sources: list[AnswerSource],
    context_chunks: list[dict[str, Any]],
    chat_history: list[ChatMessage],
) -> AsyncIterator[str]:
    # Stream valid JSON progressively while receiving model chunks.
    prefix = (
        "{"
        f'"question":{json.dumps(question)},'
        f'"sources":{json.dumps(sources)},'
        '"answer":"'
    )
    yield prefix

    try:
        stream = generate_answer(
            query=question,
            context_chunks=context_chunks,
            chat_history=[item.model_dump() for item in chat_history],
            stream=True,
        )
        for token_text in stream:
            # Escape each streamed token so final output remains valid JSON.
            yield json.dumps(token_text)[1:-1]
        yield '"}'
    except Exception as exc:
        error_text = f"Error generating answer: {exc}"
        yield json.dumps(error_text)[1:-1]
        yield '"}'


@router.post("")
async def query_notes(payload: QueryRequest):
    """Retrieve relevant notes and stream a JSON answer generated by Gemini."""
    try:
        collection: Collection = get_collection()
        context_chunks = retrieve_relevant_chunks(
            query=payload.question,
            collection=collection,
            filter_documents=payload.filter_documents,
        )
        sources = _extract_sources(context_chunks)

        return StreamingResponse(
            _stream_answer_response(
                question=payload.question,
                sources=sources,
                context_chunks=context_chunks,
                chat_history=payload.chat_history,
            ),
            media_type="application/json",
        )
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@documents_router.get("/documents")
def list_documents() -> DocumentsResponse:
    """Return unique document names currently stored in Chroma."""
    try:
        collection: Collection = get_collection()
        result = collection.get(include=["metadatas"])
        metadatas = result.get("metadatas") or []

        documents = sorted(
            {
                metadata.get("source")
                for metadata in metadatas
                if isinstance(metadata, dict) and isinstance(metadata.get("source"), str)
            }
        )
        return DocumentsResponse(documents=documents)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
